-- SQL script to insert sample data

-- INSERT data into in customer table
INSERT INTO mini_mart.customers (
    name,
    email
) VALUES
    ('Chidubem Celestine', 'dubemC@gmail.com'),
    ('Charles John', 'charlesJohn@gmail.com'),
    ('John Dean', 'johnDean@gmail.com'),
    ('Jane Robinson', 'janeRob@gmail.com'),
    ('Joseph Gates', 'josephGates@gmail.com');


-- Insert 5 rows into the products table
-- Note: product_id is auto-generated by the database
INSERT INTO mini_mart.products (product_name, category, price) VALUES
    ('Organic Apples', 'Groceries', 3.50),
    ('Whole Wheat Bread', 'Bakery', 4.25),
    ('Cheddar Cheese Block', 'Dairy', 7.99),
    ('Free-Range Eggs (Dozen)', 'Dairy', 5.49),
    ('Natural Peanut Butter', 'Pantry', 6.00);


-- Insert 5 rows into the orders table
-- This connects customers to products.
-- Note: order_id and order_date are auto-generated.
INSERT INTO mini_mart.orders (customer_id, product_id, quantity) VALUES
    (1, 2, 1), 
    (2, 5, 2),
    (1, 4, 1),
    (3, 1, 5),
    (4, 3, 1);